#!/usr/bin/env bash
# Script to transfer file from local system to remote system.
if [ $# -ge 3 ]; then
    PATH_TO_FILE=$1
    IP=$2
    USERNAME=$3
    PATH_TO_SSH_KEY=$4
    # Checks if path to identity file is specified
    if [ -z "$PATH_TO_SSH_KEY" ]; then
        scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/	
    else
        scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" \
		"$USERNAME"@"$IP":~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi	
