#!/usr/bin/env bash
# installs nginx with the configuration
#+ Listen on port 80.
#+ Returns page containing "Hello World!"
#++ at root with a curl GET request

apt-get update
apt-get install nginx -y

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen    80 default_server;
	listen    [::]:80 default_server;
	root      /etc/nginx/html;
	index     index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
